# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker compose reference guide at
# https://docs.docker.com/compose/compose-file/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
services:
  server:
    build:
      context: .
    ports:
      - 8501:8501
    environment:
      # Open AI information
      - AZURE_OPENAI_ENDPOINT=${AZURE_OPENAI_ENDPOINT}
      - AZURE_OPENAI_KEY=${AZURE_OPENAI_KEY}
      - DEPLOYMENT_NAME_4=${DEPLOYMENT_NAME_4}
      - DEPLOYMENT_NAME_35=${DEPLOYMENT_NAME_35}
      - SQL_SERVER_PASSWORD=${SQL_SERVER_PASSWORD}
    # volumes:
    #   - pokemon:/app/data
    # depends_on:
    #   - db

#   db:
#     image: "keinos/sqlite3:latest"
#     command: "echo .schema | sqlite3 /var/lib/sqlite/pokemon.db"
#     volumes:
#       - pokemon:/var/lib/sqlite

# volumes:
#   pokemon:


